// Generates the giant sdev Book in English and Bulgarian.
// Target: substantially larger than SDEV_DOCUMENTATION.md (~67KB).
import fs from 'fs';
import path from 'path';

interface Section { title: string; body: string }
interface Chapter { title: string; intro: string; sections: Section[] }

// ---------- Shared building blocks ----------

const CODE = (s: string) => '```sdev\n' + s.trim() + '\n```';

const KEYWORDS = [
  'forge','be','eternal','if','then','else','when','is','while','until','for','in',
  'escape','skip','conjure','yield','return','essence','summon','share','extends',
  'me','ancestor','attempt','rescue','finally','raise','dispatch','await','js','end',
  'window','endwindow','row','endrow','column','endcolumn','tabs','endtabs','tab','endtab',
  'group','endgroup','menu','endmenu','menuitem',
];

const BUILTINS_TABLE = [
  ['speak(value)', 'Print a value followed by a newline.'],
  ['whisper(value)', 'Print a value with no newline.'],
  ['shout(value)', 'Print a value in uppercase, attention-grabbing form.'],
  ['ask(prompt)', 'Read a line from the user (CLI) or prompt dialog (web).'],
  ['readFile(path)', 'Read the entire contents of a text file as a string.'],
  ['writeFile(path, text)', 'Write a string to a file, replacing previous contents.'],
  ['appendFile(path, text)', 'Append a string to the end of a file.'],
  ['exists(path)', 'Returns yes if the file or folder exists.'],
  ['delete(path)', 'Removes a file or folder.'],
  ['listdir(path)', 'Returns a collection of names inside a folder.'],
  ['essence(value)', 'Returns the runtime type as a string.'],
  ['morph(value, type)', 'Convert a value to another type.'],
  ['magnitude(value)', 'Length of a string or collection; absolute value of a number.'],
  ['least(...)', 'Smallest of the given values or collection.'],
  ['greatest(...)', 'Largest of the given values or collection.'],
  ['root(n, k=2)', 'k-th root of n; default square root.'],
  ['ground(n)', 'Floor; round toward negative infinity.'],
  ['elevate(n)', 'Ceiling; round toward positive infinity.'],
  ['around(n, digits=0)', 'Round to a number of decimal digits.'],
  ['random()', 'Random float in [0, 1).'],
  ['randint(a, b)', 'Random integer in [a, b].'],
  ['choose(coll)', 'Random element from a collection.'],
  ['sin(x) / cos(x) / tan(x)', 'Trigonometry in radians.'],
  ['asin/acos/atan/atan2', 'Inverse trig.'],
  ['log(x, base=e)', 'Logarithm.'],
  ['exp(x)', 'Exponential e^x.'],
  ['pi / tau / e', 'Math constants.'],
  ['gather(coll, value)', 'Append a value to a collection in place.'],
  ['pluck(coll, index)', 'Remove and return an element at index.'],
  ['portion(coll, start, end?)', 'Slice a collection.'],
  ['each(coll, fn)', 'Apply fn to each element.'],
  ['sift(coll, predicate)', 'Filter a collection.'],
  ['fold(coll, init, fn)', 'Reduce a collection to a single value.'],
  ['seek(coll, predicate)', 'First element matching predicate.'],
  ['every(coll, predicate)', 'Yes if all elements match.'],
  ['some(coll, predicate)', 'Yes if any element matches.'],
  ['zip(a, b, ...)', 'Pairs elements from multiple collections.'],
  ['enumerate(coll)', 'Pairs of (index, element).'],
  ['sequence(start, end, step=1)', 'A range of numbers.'],
  ['sort(coll, key?)', 'Sort a collection ascending.'],
  ['reverse(coll)', 'Reverse a collection or string.'],
  ['unique(coll)', 'Distinct values, preserving order.'],
  ['shatter(s, sep)', 'Split a string by separator.'],
  ['weave(coll, sep)', 'Join a collection with a separator.'],
  ['upper(s) / lower(s) / trim(s)', 'String case and whitespace.'],
  ['contains(haystack, needle)', 'Substring/element membership.'],
  ['replace(s, find, with)', 'Replace all occurrences.'],
  ['regex(pattern, s)', 'Regular expression match.'],
  ['now()', 'Current epoch milliseconds.'],
  ['today()', 'Current local date as ISO string.'],
  ['delay(ms)', 'Pause asynchronously for ms milliseconds.'],
  ['format(date, pattern)', 'Format a date.'],
  ['env(name) / argv() / exit(code)', 'Process and OS interaction.'],
  ['osinfo()', 'Returns a dictionary about the host OS.'],
  ['base64encode/decode, hexencode/decode', 'Binary encodings.'],
  ['jsonencode(v) / jsondecode(s)', 'JSON serialization.'],
  ['fetch(url, opts?)', 'Async HTTP request.'],
  ['matrix(rows) / matmul / inverse / transpose / det', 'Linear algebra.'],
  ['buffer(size) / pointer(v) / deref(p)', 'Low-level memory primitives.'],
  ['spawn(fn) / schedule() / syscall(name, args) / gc()', 'Kernel / scheduler primitives.'],
  // UI
  ['window(title, w, h)', 'Open a window. End with endwindow.'],
  ['heading(text, level=1)', 'A bold heading.'],
  ['label(text)', 'A line of text.'],
  ['paragraph(text)', 'A paragraph of body text.'],
  ['button(label, onclick, variant?)', 'Clickable button. Variants: primary, secondary, ghost, destructive.'],
  ['input(bind, placeholder?, kind?)', 'Text input bound by name. Kind: text, number, password, email, url.'],
  ['textarea(bind, placeholder?, rows?)', 'Multi-line input.'],
  ['checkbox(bind, label)', 'Boolean toggle with label.'],
  ['radio(bind, value, label)', 'Radio button bound by name.'],
  ['slider(bind, min, max, step=1)', 'Numeric slider.'],
  ['select(bind, options, placeholder?)', 'Dropdown of options.'],
  ['image(src, w?, h?, alt?)', 'Display an image.'],
  ['link(text, url, newtab=yes)', 'Open a URL.'],
  ['progress(value, max=100)', 'Determinate progress bar.'],
  ['divider() / spacer(size?)', 'Visual layout helpers.'],
  ['row()/endrow, column()/endcolumn, group(title)/endgroup', 'Layout containers.'],
  ['tabs()/endtabs, tab(title)/endtab', 'Tabbed sections.'],
  ['table(headers, rows)', 'A data table.'],
  ['menu(title)/endmenu, menuitem(title, onclick)', 'Menus and items.'],
  ['uiget(name) / uiset(name, value)', 'Read or write a reactive value.'],
];

// ---------- English Chapters ----------

const EN_CHAPTERS: Chapter[] = [
  {
    title: 'Introduction',
    intro: 'Welcome to **The sdev Book** — the definitive, comprehensive reference for the sdev programming language. sdev is a modern, expressive language with a uniquely human-readable syntax (`forge`, `be`, `speak`, `conjure`, `summon`) designed to make code feel like prose without sacrificing power, performance, or expressiveness.\n\nThis book is *long*. That is intentional. Programming languages are rich worlds, and sdev — with its readable syntax, dual runtimes, UI toolkit, kernel, bytecode VM, and 26-language source support — has more surface area than most. We want one document you can keep open and trust.',
    sections: [
      { title: 'Why sdev?', body: 'sdev was created to bridge the gap between *talking about code* and *writing code*. Traditional languages force you into algebraic shorthand (`x = 1`, `def`, `var`). sdev replaces these with verbs and nouns that carry meaning: `forge x be 1`. The result is code that reads like a recipe, an essay, or a spell — depending on your style.\n\nsdev also takes seriously the idea that **a language should ship with everything you need**: a UI toolkit, a graphics canvas, a mapping API, a kernel-style task scheduler, a bytecode VM, AI-aware tooling, and translations of the keywords into 26 spoken languages. You should not need to install five libraries before drawing a circle.' },
      { title: 'A Brief History', body: 'sdev started as an experiment in *prose-shaped* programming — could a language with `forge x be 1` feel as natural to read aloud as English? The first interpreter was a 400-line tree-walker. From there it grew into two parallel runtimes (JavaScript and Python), a bytecode compiler, a virtual kernel, and an in-browser IDE. Today sdev is used for teaching, scripting, prototyping interactive UIs, and producing maps and data visualisations.' },
      { title: 'Who Should Read This Book', body: 'This book is for everyone:\n\n- **Complete beginners** learning to program for the first time. Chapters 1–6 are written gently, with annotated examples.\n- **Professional developers** exploring an expressive new language. Skim the basics and dive into Chapters 11+ for concurrency, the kernel, and bytecode internals.\n- **Educators** teaching computational thinking. The verb-based vocabulary maps cleanly onto English (and 25 other languages).\n- **Language designers** studying alternative syntactic paradigms. Chapter 27 dissects design decisions.\n\nEach chapter starts gentle and ramps up.' },
      { title: 'How To Use This Book', body: 'Read sequentially the first time. Skim later. Every example is runnable in the **online IDE** at https://s-dev.lovable.app or with the offline Python/JS interpreters available from the Downloads menu.\n\nThe single best way to learn sdev is to **type the examples** — do not just read them. Modify them. Break them on purpose. When something does not behave as expected, that is when you learn.' },
      { title: 'Conventions', body: 'Code blocks use the `sdev` syntax. Output is shown in `// =>` comments. Notes labeled **TIP**, **WARNING**, **DEEP DIVE**, and **HISTORY** signal important context. Bulgarian translations of every chapter are in `sdev-book-bg.md`.\n\nWe write `forge x be 1` rather than `forge x = 1` throughout. Both are valid; `be` is preferred because it reads aloud naturally.' },
      { title: 'A First Taste', body: CODE(`// A complete sdev program.\nforge greet be conjure(name): "Hello, " + name end\nspeak(greet("world"))\n// => Hello, world`) + '\n\nIf that looks unusual, good. Read on; in five chapters it will feel obvious.' },
    ],
  },
  {
    title: 'Getting Started',
    intro: 'In this chapter you will install sdev (or skip installation by using the web IDE), write your first program, and understand the moving parts of a project.',
    sections: [
      { title: 'Installing sdev', body: 'There are several ways to run sdev:\n\n1. **Web IDE** — no install, open https://s-dev.lovable.app/ide. Works on any modern browser.\n2. **JavaScript runtime** — `node sdev-interpreter.js my-file.sdev`. A single ~120 KB file with no dependencies.\n3. **Python runtime** — `python sdev-interpreter.py my-file.sdev`. Useful when embedding into Python tooling.\n4. **VS Code extension** — `.vsix` from the Downloads menu. Adds syntax highlighting, snippets, and a Run command.\n5. **Windows installer** — bundled batch installer with a tiny editor.\n\nAll runtimes share strict feature parity. A program that runs in one will run in the other, with the exception of host-only APIs (Leaflet maps require the JS runtime + a browser DOM).' },
      { title: 'Your First Program', body: 'Create a file `hello.sdev`:\n\n' + CODE(`speak("Hello, world!")`) + '\n\nRun it:\n\n```bash\nnode sdev-interpreter.js hello.sdev\n# => Hello, world!\n```\n\nCongratulations — you are an sdev programmer.' },
      { title: 'The REPL', body: 'Start the REPL with `python sdev-interpreter.py` (no arguments). Type expressions and they will be evaluated immediately:\n\n```\nsdev> forge x be 10\nsdev> x * 2\n20\nsdev> :quit\n```\n\nUseful REPL meta-commands: `:quit`, `:reset`, `:load file.sdev`, `:save session.sdev`, `:type expr`.' },
      { title: 'Project Structure', body: 'A typical sdev project has:\n\n- `main.sdev` — entry point\n- `lib/` — your modules\n- `assets/` — images, data files\n- `README.md` — documentation\n- `manifest.sdev` — optional package manifest for `summon`\n\nThere is no required layout. sdev is happy with a single file.' },
      { title: 'Running From the IDE', body: 'In the web IDE, press `Ctrl+Enter` (or `Cmd+Enter` on macOS) to run the active tab. The output panel shows printed text; the **App** panel shows UI windows; the **Canvas** panel shows graphics; the **Map** panel shows Leaflet output. The IDE auto-saves to your account if you are signed in.' },
      { title: 'Anatomy of a Program', body: 'An sdev source file is a sequence of statements. Statements include declarations, expressions, control structures, function and class definitions, and imports. Whitespace is significant only inside strings; indentation is for humans, `end` is for the parser.' },
      { title: 'Editor Setup', body: 'For non-IDE workflows, the VS Code extension bundles syntax + snippets. Vim users can drop the `sdev.vim` file into `~/.vim/syntax/`. Emacs users can use `sdev-mode.el` from the extension folder.' },
      { title: 'Common Pitfalls For Beginners', body: '- Forgetting `end` after `if`, `while`, or `conjure`. The error message will tell you the line of the unmatched opener.\n- Using `=` instead of `be` for assignment. Both work; `be` is canonical.\n- Mixing `yes`/`no` with `true`/`false`. Both are accepted; pick one and stay consistent in a file.' },
    ],
  },
  {
    title: 'Variables and Values',
    intro: 'Every program manipulates data. In sdev you create variables with `forge` and bind them with `be`. Values are typed dynamically — sdev figures out the type at runtime, but you can inspect, convert, and constrain types as needed.',
    sections: [
      { title: 'Forging Variables', body: CODE(`forge name be "Ada"\nforge age be 36\nforge alive be yes`) + '\n\nThe `forge` keyword introduces a *new* binding in the current scope. Re-assignment uses just the name:\n\n' + CODE(`name be "Lovelace"`) + '\n\nReassignment without `forge` keeps the variable in its original scope. This rule prevents accidental shadowing of outer-scope variables.' },
      { title: 'The Six Primitive Types', body: 'sdev recognises six primitive types:\n\n| Type | Examples | Notes |\n|---|---|---|\n| **number** | `42`, `3.14`, `-7` | One numeric type covers ints and floats. |\n| **string** | `"hi"`, `\'hi\'` | Unicode by default. |\n| **boolean** | `yes`, `no` (or `true`/`false`) | |\n| **void** | `nothing` | The absence of a value. |\n| **collection** | `[1,2]`, `{a: 1}` | Lists and dictionaries. |\n| **function** | `conjure(): ... end` | First-class. |' },
      { title: 'Type Inspection', body: 'Use `essence(value)` to ask what type a value is.\n\n' + CODE(`speak(essence(42))      // => "number"\nspeak(essence("hi"))    // => "string"\nspeak(essence(yes))     // => "boolean"\nspeak(essence([1,2]))   // => "collection"\nspeak(essence(speak))   // => "function"`) },
      { title: 'Type Conversion (`morph`)', body: '`morph(value, type_name)` converts between types when sensible.\n\n' + CODE(`forge n be morph("42", "number")\nspeak(n + 1)  // => 43\nforge s be morph(3.14, "string")\nspeak(s + " is pi")  // => "3.14 is pi"`) + '\n\nIf the conversion is impossible, `morph` raises a runtime error. Wrap with `attempt/rescue` to handle gracefully.' },
      { title: 'Constants (`eternal`)', body: 'Prefix with `eternal` to mark a binding immutable.\n\n' + CODE(`eternal forge PI be 3.14159\nPI be 4   // => error: cannot rebind eternal binding`) + '\n\n**TIP**: use `eternal` liberally. Future readers (including your future self) benefit from knowing what does not change.' },
      { title: 'Naming Rules', body: 'Identifiers must begin with a letter or underscore and may contain letters, digits, and underscores. Reserved keywords cannot be used. snake_case is conventional for variables and functions; PascalCase for classes; SCREAMING_CASE for `eternal` constants.' },
      { title: 'Scope', body: 'sdev uses **lexical scoping**. A `forge` inside a block creates a new local binding that shadows outer bindings. The outer binding is restored when the block ends. Functions capture variables by reference, creating closures.' },
      { title: 'Nothing, Truthiness, Equality', body: '`nothing` is the only value of type `void`. In boolean contexts, the falsy values are: `no`, `nothing`, `0`, `""`, and the empty collection `[]`/`{}`. Everything else is truthy.\n\n`equals` (alias `==`) compares by value for primitives and by structure for collections. `same` compares by reference identity.' },
      { title: 'Numbers In Detail', body: 'Numbers are 64-bit floating point internally, with a transparent integer fast-path. Integer arithmetic preserves precision up to 2^53. Use `bigint(n)` to opt into arbitrary-precision integers.' },
      { title: 'Strings In Detail', body: 'Strings are immutable Unicode. Indexing returns a single-character string. Negative indices count from the end. Common operations: `upper`, `lower`, `trim`, `reverse`, `contains`, `replace`, `shatter`, `weave`. Triple-quoted strings preserve newlines.' },
    ],
  },
  {
    title: 'Operators and Expressions',
    intro: 'sdev supports the usual arithmetic, comparison, and logical operators, with English-word aliases for prose-style code.',
    sections: [
      { title: 'Arithmetic', body: 'Standard symbols: `+`, `-`, `*`, `/`, `%` (modulo), `**` (exponent). Integer division uses `//`. Unary `-` negates.' },
      { title: 'Comparison', body: '`==`, `!=`, `<`, `>`, `<=`, `>=`. The aliases `equals`, `differs`, `below`, `above`, `belowOr`, `aboveOr` are available for prose-style code:\n\n' + CODE(`if age above 18 then speak("Adult") end`) },
      { title: 'Logical', body: '`and`, `or`, `not`. Short-circuit evaluation is guaranteed. The symbols `&&`, `||`, `!` also work but are less idiomatic.' },
      { title: 'String Operators', body: 'Concatenate with `+`. Repeat with `*`:\n\n' + CODE(`speak("ha" * 3)  // => hahaha`) + '\n\nInterpolation uses backticks:\n\n' + CODE("forge n be 7\nspeak(`There are ${n} cats`)") },
      { title: 'Membership', body: '`x in coll` returns `yes` if `x` is in a collection, key in a dictionary, or substring in a string.' },
      { title: 'Pipelines (`|>`)', body: 'The pipeline operator passes a value as the first argument of the next function:\n\n' + CODE(`"  Hello  " |> trim |> upper |> speak  // => HELLO`) },
      { title: 'Operator Precedence', body: 'From tightest to loosest: `**`, unary `-`/`not`, `* / // %`, `+ -`, comparisons, `and`, `or`, `|>`, assignment. Parentheses always win.' },
      { title: 'Truthy Conversions', body: 'Boolean operators return *the value*, not a boolean: `forge x be value or "default"` is a common idiom for fallbacks.' },
    ],
  },
  {
    title: 'Control Flow',
    intro: 'sdev offers familiar control structures with an English-friendly twist.',
    sections: [
      { title: 'If / Then / Else', body: CODE(`if score above 90 then\n  speak("Excellent")\nelse if score above 70 then\n  speak("Good")\nelse\n  speak("Try again")\nend`) },
      { title: 'When (Pattern Match)', body: 'A multi-branch conditional that reads top-to-bottom:\n\n' + CODE(`when:\n  is x below 0 then speak("negative")\n  is x equals 0 then speak("zero")\n  is x above 0 then speak("positive")\n  else speak("not a number")\nend`) },
      { title: 'While And Until', body: CODE(`while count below 10:\n  speak(count)\n  count be count + 1\nend\n\nuntil ready:\n  poll()\nend`) },
      { title: 'For ... In', body: CODE(`for name in ["Ada", "Grace", "Linus"]:\n  speak("Hi " + name)\nend\n\nfor i in sequence(1, 10):\n  speak(i)\nend`) },
      { title: 'Escape And Skip', body: '`escape` exits the innermost loop; `skip` jumps to the next iteration.\n\n' + CODE(`for n in sequence(1, 100):\n  if n % 2 == 0 then skip end\n  if n above 20 then escape end\n  speak(n)\nend`) },
      { title: 'Labelled Loops', body: 'Prefix a loop with `label name:` and use `escape name` or `skip name` to break out of nested loops directly.' },
      { title: 'Match (Destructuring)', body: 'Extract from collections inline:\n\n' + CODE(`forge [first, *rest] be [1, 2, 3, 4]\nforge {name, age} be {name: "Ada", age: 36}`) },
    ],
  },
  {
    title: 'Functions',
    intro: 'Functions are first-class values in sdev. Declare with `conjure`; pass them around like any other data.',
    sections: [
      { title: 'Defining a Function', body: CODE(`conjure greet(name be "stranger"):\n  speak("Hello, " + name)\nend\n\ngreet()        // => Hello, stranger\ngreet("Ada")   // => Hello, Ada`) },
      { title: 'Default and Keyword Arguments', body: 'Defaults attach with `be`. Callers may use positional or keyword form:\n\n' + CODE(`conjure rect(width be 10, height be 5):\n  return width * height\nend\nspeak(rect(height: 8))  // => 80`) },
      { title: 'Variadic Arguments', body: '`*items` collects extra positional arguments. `**opts` collects keyword arguments.' },
      { title: 'Returning Values', body: 'Use `return value` to exit early. The last expression in a function is its implicit return value.' },
      { title: 'Anonymous Functions (Lambdas)', body: CODE(`forge double be (n) => n * 2\nspeak(double(7))  // => 14`) + '\n\nLambdas capture surrounding variables, forming closures.' },
      { title: 'Closures', body: CODE(`conjure counter():\n  forge n be 0\n  return () => { n be n + 1; return n }\nend\nforge tick be counter()\nspeak(tick())  // => 1\nspeak(tick())  // => 2`) },
      { title: 'Higher-Order Functions', body: '`each`, `sift`, `fold`, `seek`, `every`, `some` accept functions. They form the backbone of idiomatic data processing.' },
      { title: 'Recursion', body: 'sdev supports unbounded recursion (subject to the host stack). Use the `tailcall` modifier to enable tail-call optimisation:\n\n' + CODE(`conjure tailcall sum_to(n, acc be 0):\n  if n equals 0 then return acc end\n  return sum_to(n - 1, acc + n)\nend`) },
      { title: 'Generators (`yield`)', body: 'Functions that `yield` produce iterators on demand:\n\n' + CODE(`conjure naturals():\n  forge n be 0\n  while yes:\n    yield n\n    n be n + 1\n  end\nend`) },
      { title: 'Decorators', body: 'A decorator wraps a function with extra behaviour. Apply with `@`:\n\n' + CODE(`@logged\nconjure work(): speak("doing work") end`) },
    ],
  },
  {
    title: 'Collections',
    intro: 'Collections are how sdev programs store many values together. The two core kinds are **lists** and **dictionaries**.',
    sections: [
      { title: 'Lists', body: CODE(`forge nums be [1, 2, 3]\nspeak(nums[0])             // => 1\nspeak(nums[-1])            // => 3\ngather(nums, 4)            // [1,2,3,4]\nforge head be pluck(nums, 0)`) },
      { title: 'Dictionaries', body: CODE(`forge user be {name: "Ada", age: 36}\nspeak(user.name)          // => Ada\nspeak(user["age"])        // => 36\nuser.email be "ada@x.com"`) },
      { title: 'Slicing', body: '`portion(coll, start, end?)` returns a sub-collection. Negative indices count from the end. Omit `end` to slice to the end.' },
      { title: 'Map / Filter / Reduce', body: CODE(`forge squares be each([1,2,3,4], (n) => n * n)\nforge evens be sift([1,2,3,4], (n) => n % 2 equals 0)\nforge total be fold([1,2,3,4], 0, (a, b) => a + b)`) },
      { title: 'Sets', body: 'Use `unique(coll)` to deduplicate. For frequent membership tests, `set(coll)` returns a hash-set wrapper.' },
      { title: 'Tuples', body: 'Immutable, fixed-length collections written `(a, b)`. Useful for returning multiple values:\n\n' + CODE(`conjure divmod(a, b): return (a // b, a % b) end\nforge (q, r) be divmod(17, 5)`) },
      { title: 'Iteration Idioms', body: 'Use `for ... in`, `enumerate`, and `zip` to traverse collections. Generators are lazy; lists are eager.' },
      { title: 'Performance Notes', body: 'Lists are dynamic arrays; appends are amortised O(1). Dictionaries are open-address hash maps; lookup is amortised O(1). Avoid `pluck(coll, 0)` in hot loops — it is O(n). Use a deque (`deque()`) for fast front operations.' },
    ],
  },
  {
    title: 'Strings In Depth',
    intro: 'Strings get a chapter of their own because text is everywhere — input, output, file paths, network protocols, UI labels.',
    sections: [
      { title: 'Literals', body: 'Single quotes (`\'hi\'`) and double quotes (`"hi"`) are equivalent. Triple quotes (`"""..."""`) preserve newlines. Backticks support `${interpolation}`.' },
      { title: 'Indexing And Slicing', body: 'Strings are indexable like lists. They are immutable; operations return new strings.' },
      { title: 'Searching', body: 'Use `contains(s, sub)`, `indexOf(s, sub)`, `lastIndexOf(s, sub)`. For regex, use `regex(pattern, s)`.' },
      { title: 'Manipulation', body: '`upper`, `lower`, `trim`, `lstrip`, `rstrip`, `replace(s, find, with)`, `shatter(s, sep)`, `weave(coll, sep)`.' },
      { title: 'Encoding', body: '`base64encode/decode`, `urlencode/decode`, `hexencode/decode`. All accept strings or byte buffers.' },
      { title: 'Formatting', body: 'Use backtick interpolation, or `format(template, args)` with `%s`, `%d`, `%.2f` style placeholders.' },
      { title: 'Regular Expressions', body: CODE(`forge m be regex("(\\\\w+)@(\\\\w+)", "ada@example")\nspeak(m.groups[0])  // => ada`) },
      { title: 'Unicode And Locales', body: 'sdev strings are sequences of Unicode codepoints. `lower` and `upper` are locale-aware when a locale is set with `locale("bg_BG")`.' },
    ],
  },
  {
    title: 'Object-Oriented Programming',
    intro: 'sdev includes a full OOP system built on the keywords `essence` (define a class), `summon` (instantiate), `share` (declare instance/class fields), `extends` (inherit), `me` (this), and `ancestor` (super).',
    sections: [
      { title: 'Defining a Class', body: CODE(`essence Dog:\n  share name\n  share breed be "mutt"\n\n  conjure init(name, breed be "mutt"):\n    me.name be name\n    me.breed be breed\n  end\n\n  conjure bark():\n    speak(me.name + " woofs!")\n  end\nend`) },
      { title: 'Creating Instances', body: CODE(`forge rex be summon Dog(name: "Rex", breed: "Labrador")\nrex.bark()`) },
      { title: 'Inheritance', body: CODE(`essence Puppy extends Dog:\n  conjure bark():\n    ancestor.bark()\n    speak("(tiny)")\n  end\nend`) },
      { title: 'Class Methods And Fields', body: 'Prefix with `static` to attach to the class rather than instances:\n\n' + CODE(`essence Counter:\n  static share total be 0\n  static conjure tick(): Counter.total be Counter.total + 1 end\nend`) },
      { title: 'Mixins (`weave`)', body: 'Include reusable methods from another module:\n\n' + CODE(`essence Bird weave Flyable, Singable: end`) },
      { title: 'Operator Overloading', body: 'Implement special methods like `__add__`, `__eq__`, `__str__` to customise built-in operators on your class.' },
      { title: 'Properties', body: 'Decorate a method with `@property` to expose it as a field. `@setter` makes it writable.' },
      { title: 'Abstract Classes And Interfaces', body: 'Mark a method `abstract conjure name()` to require subclasses to provide it. `interface` declares only signatures.' },
    ],
  },
  {
    title: 'Error Handling',
    intro: 'Programs fail. sdev gives you precise, ergonomic tools to handle failure.',
    sections: [
      { title: 'Raising Errors', body: CODE(`raise "Out of fuel"\nraise FuelError("Out of fuel", code: 42)`) },
      { title: 'Attempt / Rescue / Finally', body: CODE(`attempt:\n  forge data be readFile("missing.txt")\nrescue err:\n  speak("Could not read: " + err.message)\nfinally:\n  speak("done")\nend`) },
      { title: 'Error Types', body: 'Built-in error types include `TypeError`, `ValueError`, `IOError`, `KeyError`, `IndexError`, `NetworkError`, `TimeoutError`, `SyntaxError`. Define your own by extending `essence Error`.' },
      { title: 'Multiple Rescues', body: 'A single `attempt` may have several `rescue` clauses, each matched by error type:\n\n' + CODE(`attempt:\n  doWork()\nrescue NetworkError as e:\n  retry()\nrescue err:\n  raise err\nend`) },
      { title: 'Re-raising', body: 'Inside a `rescue`, call `raise` with no argument to re-throw the current error. Useful for logging then propagating.' },
      { title: 'Stack Traces', body: 'Errors carry a `.trace` field — a list of frames with file, line, and function name. `speak(err.trace)` prints a formatted trace.' },
      { title: 'Assertions', body: 'Use `ensure(condition, "message")` to validate invariants. Failed assertions raise `AssertionError`.' },
      { title: 'Defensive Programming Idioms', body: 'Validate inputs at function boundaries with `ensure`. Use `attempt/rescue` only at boundaries you genuinely intend to recover at — not as silent error swallowers.' },
    ],
  },
  {
    title: 'Concurrency',
    intro: 'sdev embraces cooperative concurrency. Tasks share a single thread but yield to one another at well-defined points.',
    sections: [
      { title: 'Async Functions', body: 'Any function may be `async`. Inside, use `await` to wait for an asynchronous result without blocking other tasks.' },
      { title: 'Dispatch And Await', body: CODE(`async conjure fetchUser(id):\n  forge res be await fetch("/users/" + id)\n  return jsondecode(res.body)\nend\n\nforge promise be dispatch fetchUser(7)\nforge user be await promise\nspeak(user.name)`) },
      { title: 'Parallel Composition', body: '`await all([p1, p2])` waits for several promises in parallel. `await any([p1, p2])` returns the first to resolve. `await race([p1, p2])` returns the first settled (resolve or reject).' },
      { title: 'Channels', body: '`channel()` creates a queue. `send(ch, v)` and `forge v be await receive(ch)` move values between tasks.' },
      { title: 'Cancellation', body: 'Promises support `cancel(p)`. Inside `attempt`, `rescue CancelledError` cleans up gracefully.' },
      { title: 'Time And Delay', body: '`await delay(1000)` pauses for one second. `every(ms, fn)` schedules a repeating task.' },
      { title: 'The Kernel', body: 'Under the hood, all tasks live in a virtual kernel with its own scheduler. See Chapter 18 for syscalls and direct task spawning.' },
    ],
  },
  {
    title: 'Modules and Libraries',
    intro: 'Real programs span multiple files. sdev modules are simply other `.sdev` files. The `summon` keyword imports them, locally or from the network.',
    sections: [
      { title: 'Local Modules', body: '`summon "./utils.sdev" as u` makes `u.fnName` available. Symbols can be selectively imported: `summon "./utils.sdev" {add, mul}`.' },
      { title: 'Gist Packages', body: 'sdev uses **GitHub Gists** as a decentralised package registry. `summon "gist:abc123/util.sdev" as util` fetches and caches a gist on first use.' },
      { title: 'Versioning', body: 'Pin a gist to a specific revision: `summon "gist:abc123@v1.2.0/util.sdev"`. Without a version, the latest revision is used and cached for 24 hours.' },
      { title: 'Manifests', body: 'A `manifest.sdev` file may declare dependencies. Run `sdev install` to fetch them all upfront.' },
      { title: 'Authoring A Gist Module', body: 'Any file with public `conjure` and `essence` declarations is a valid module. Use `share private` to hide internals.' },
      { title: 'Module Scope', body: 'Each module has its own top-level scope. `summon` does not pollute the importer\'s globals unless you write `summon * from ...`.' },
      { title: 'Dynamic Loading', body: 'Use `loadModule(url)` to import at runtime. Useful for plugins.' },
    ],
  },
  {
    title: 'The UI Toolkit',
    intro: 'sdev ships with a complete declarative UI toolkit for building windows, forms, dashboards, and small apps. The same code runs in the IDE App panel and (via the JS interpreter + DOM) in the browser.',
    sections: [
      { title: 'Windows', body: '`window(title, width, height)` opens a window. End with `endwindow`. Width and height are CSS pixels.\n\n' + CODE(`window("My App", 480, 600)\n  heading("Welcome", 1)\n  paragraph("Hello there.")\nendwindow`) },
      { title: 'Headings, Labels, Paragraphs', body: '`heading(text, level=1)` for titles (levels 1–6). `label(text)` for short lines. `paragraph(text)` for body copy.' },
      { title: 'Buttons', body: CODE(`button("Click me", () => speak("clicked"), "primary")`) + '\n\nVariants: `primary`, `secondary`, `ghost`, `destructive`, `link`. Pass an `icon:` keyword for an icon prefix.' },
      { title: 'Inputs', body: CODE(`input("name", "Your name")\ninput("age", "Age", "number")\ninput("password", "Password", "password")`) + '\n\nThe first argument is the *bind name* — read it later with `uiget("name")`.' },
      { title: 'Textareas', body: '`textarea(bind, placeholder, rows)` for multi-line input.' },
      { title: 'Checkboxes And Radios', body: CODE(`checkbox("agree", "I agree")\nradio("plan", "free", "Free")\nradio("plan", "pro", "Pro")`) },
      { title: 'Sliders And Selects', body: CODE(`slider("volume", 0, 100, 1)\nselect("country", ["BG", "US", "DE"], "Pick one")`) },
      { title: 'Tables', body: CODE(`table(["Name", "Age"], [\n  ["Ada", 36],\n  ["Grace", 85],\n])`) },
      { title: 'Tabs', body: CODE(`tabs()\n  tab("Home")\n    paragraph("Welcome.")\n  endtab\n  tab("Settings")\n    checkbox("dark", "Dark mode")\n  endtab\nendtabs`) },
      { title: 'Menus', body: CODE(`menu("File")\n  menuitem("New", () => newDoc())\n  menuitem("Open", () => openDoc())\nendmenu`) },
      { title: 'Layout: Rows, Columns, Groups', body: 'Use `row()/endrow` for horizontal stacks, `column()/endcolumn` for vertical, `group("title")/endgroup` for bordered cards.' },
      { title: 'Reactive Values', body: 'All bound widgets read from and write to a reactive store. `uiget(name)` reads; `uiset(name, value)` writes and re-renders the window.' },
      { title: 'Event Handlers', body: 'Buttons, menu items, and many widgets accept a callback. The callback runs in the same scope as the program; closures over outer variables work as expected.' },
      { title: 'Customisation', body: 'Pass a final dictionary of options to most widgets:\n\n' + CODE(`button("Open URL", () => {}, "primary", { url: "https://sdev.codes", icon: "external" })\nimage("/logo.png", 200, 100, "Logo")`) },
      { title: 'A Complete Example', body: CODE(`forge todos be []\nwindow("Todos", 360, 480)\n  heading("My Todos", 2)\n  input("new", "What to do?")\n  button("Add", () => {\n    gather(todos, uiget("new"))\n    uiset("new", "")\n  }, "primary")\n  divider()\n  for t in todos:\n    row()\n      checkbox("done_" + t, t)\n    endrow\n  end\nendwindow`) },
    ],
  },
  {
    title: 'Graphics and Canvas',
    intro: 'For drawing and animation, sdev provides a 2D canvas API.',
    sections: [
      { title: 'Opening A Canvas', body: '`canvas(width, height)` opens a drawing surface in the IDE Canvas panel.' },
      { title: 'Drawing Primitives', body: '`fill(color)`, `stroke(color)`, `lineWidth(n)`, `rect(x,y,w,h)`, `circle(x,y,r)`, `line(x1,y1,x2,y2)`, `polygon([pts])`, `text(s,x,y)`.' },
      { title: 'Colors', body: 'Accept named CSS colors, `#rrggbb`, `rgb(r,g,b)`, `hsl(h,s,l)`, or `rgba(r,g,b,a)`.' },
      { title: 'Animation', body: '`frame(fn)` calls `fn(t)` once per frame with the elapsed time. `requestStop()` halts the loop.' },
      { title: 'Images And Sprites', body: '`loadImage(url)` returns a future image. `drawImage(img, x, y, w, h)` draws it.' },
      { title: 'Transforms', body: '`translate(dx,dy)`, `rotate(rad)`, `scale(sx,sy)`. Save and restore state with `push()` / `pop()`.' },
      { title: 'Mouse And Keyboard', body: '`onmouse((evt) => ...)`, `onkey((evt) => ...)`. Events carry `x`, `y`, `key`, `button`.' },
      { title: 'Bouncing Ball Example', body: CODE(`canvas(400, 400)\nforge x be 200; forge y be 200; forge dx be 3; forge dy be 2\nframe((t) => {\n  fill("black"); rect(0, 0, 400, 400)\n  fill("cyan"); circle(x, y, 20)\n  x be x + dx; y be y + dy\n  if x below 0 or x above 400 then dx be -dx end\n  if y below 0 or y above 400 then dy be -dy end\n})`) },
    ],
  },
  {
    title: 'Maps and GIS',
    intro: 'sdev integrates with Leaflet for interactive maps. The mapping API is host-specific (browser only).',
    sections: [
      { title: 'Opening A Map', body: '`map(lat, lon, zoom)` opens a map centred on the given coordinates.' },
      { title: 'Markers And Popups', body: '`marker(lat, lon, "label")` drops a marker. `popup(lat, lon, "html")` shows a popup.' },
      { title: 'Tile Layers', body: '`tiles(url_template, opts)` switches the basemap. Built-in styles: `osm`, `dark`, `satellite`.' },
      { title: 'Polylines And Polygons', body: '`polyline([[lat,lon], ...], "color")`. `polygon([[lat,lon], ...], "color")`.' },
      { title: 'GeoJSON', body: '`geojson(url_or_object)` adds an entire GeoJSON feature collection.' },
      { title: 'Heatmaps And Clustering', body: '`heatmap(points)` and `cluster(points)` visualise dense data.' },
      { title: 'Events', body: '`onclick((lat, lon) => ...)` reacts to map clicks. `onzoom((z) => ...)` reacts to zoom changes.' },
      { title: 'Routing And Distance', body: '`distance((lat1,lon1), (lat2,lon2))` returns metres. `route(from, to)` returns a polyline via OSRM.' },
      { title: 'A Complete Map Example', body: CODE(`map(42.6977, 23.3219, 12)\nmarker(42.6977, 23.3219, "Sofia")\npolyline([[42.6, 23.3], [42.7, 23.4]], "cyan")`) },
    ],
  },
  {
    title: 'The Standard Library',
    intro: 'A reference of the most-used built-in functions. The complete list is in `SDEV_DOCUMENTATION.md`.',
    sections: [
      { title: 'Built-in Function Table', body: '| Function | Description |\n|---|---|\n' + BUILTINS_TABLE.map(([n,d]) => `| \`${n}\` | ${d} |`).join('\n') },
      { title: 'I/O', body: '`speak`, `whisper`, `shout`, `ask`, `readFile`, `writeFile`, `appendFile`, `exists`, `delete`, `listdir`.' },
      { title: 'Math', body: '`magnitude`, `least`, `greatest`, `root`, `ground`, `elevate`, `around`, `random`, `randint`, `choose`, `sin/cos/tan`, `log`, `exp`, `pi`, `tau`, `e`.' },
      { title: 'Collections', body: '`gather`, `pluck`, `portion`, `each`, `sift`, `fold`, `seek`, `every`, `some`, `zip`, `enumerate`, `sequence`, `sort`, `reverse`, `unique`, `set`, `deque`.' },
      { title: 'Strings', body: '`upper`, `lower`, `trim`, `reverse`, `contains`, `replace`, `shatter`, `weave`, `regex`, `format`.' },
      { title: 'Time', body: '`now`, `today`, `delay`, `every`, `format`, `parseDate`, `timezone`.' },
      { title: 'Network', body: '`fetch`, `websocket`, `download`.' },
      { title: 'System', body: '`env`, `argv`, `exit`, `osinfo`, `cwd`, `cd`.' },
      { title: 'Encoding', body: '`base64encode/decode`, `hexencode/decode`, `urlencode/decode`, `jsonencode/decode`, `csv`, `xml`.' },
      { title: 'Cryptography', body: '`hash(s, alg="sha256")`, `hmac(key, msg, alg)`, `uuid()`, `randomBytes(n)`.' },
    ],
  },
  {
    title: 'Tooling',
    intro: 'Editors, linters, debuggers, and the bytecode compiler.',
    sections: [
      { title: 'The Web IDE', body: 'A full-featured browser IDE at https://s-dev.lovable.app/ide. Includes a file tree, tabs, command palette, terminal, output, App preview, canvas, map, settings, and a chatbot.' },
      { title: 'VS Code Extension', body: 'Download `.vsix` from the Downloads menu. Provides syntax highlighting, snippets, and a Run command (`F5`).' },
      { title: 'CLI Reference', body: '`node sdev-interpreter.js [opts] [file]`\n\n- `--repl` start REPL\n- `--compile file.sdev` produce `file.sdevc`\n- `--exec file.sdevc` run bytecode\n- `--lang bg` set source language\n- `--ast` print parse tree\n- `--time` print execution timing' },
      { title: 'Bytecode Compiler', body: 'Compile to `.sdevc` for faster startup: `node sdev-interpreter.js --compile main.sdev`. Run with `--exec main.sdevc`.' },
      { title: 'The sdev Assistant', body: 'In-IDE AI chatbot that explains code, generates examples, and debugs runtime errors via a self-test loop.' },
      { title: 'Linter', body: '`sdev lint file.sdev` checks for unused variables, missing `end`s, suspicious comparisons, and shadowed `eternal` bindings.' },
      { title: 'Formatter', body: '`sdev format file.sdev` rewrites a file in canonical style. Idempotent.' },
      { title: 'Debugger', body: 'Place `breakpoint()` in code; in the IDE, execution pauses at that line and the variables panel becomes inspectable. Step with F10.' },
      { title: 'Test Runner', body: '`sdev test` discovers `*_test.sdev` files and runs every `conjure test_*` function. Use `expect(value).toBe(other)` for assertions.' },
    ],
  },
  {
    title: 'Advanced Topics',
    intro: 'Power-user features for systems, performance, embedding, and unusual workflows.',
    sections: [
      { title: 'JavaScript Interop', body: 'Embed raw JS with the `js` keyword:\n\n' + CODE(`js { console.log("native") }`) + '\n\nMulti-line `js { ... }` blocks share scope with the surrounding sdev program. Values flow both ways.' },
      { title: 'Matrix Math', body: '`matrix([[1,2],[3,4]])`, `matmul(a, b)`, `inverse(a)`, `transpose(a)`, `det(a)`. Useful for graphics, linear algebra, and ML toy projects.' },
      { title: 'Buffers and Pointers', body: '`buffer(size)`, `pointer(value)`, `deref(p)`. For binary protocol work.' },
      { title: 'The Virtual Kernel', body: 'sdev includes a tiny virtual OS kernel. `spawn(fn)` creates a task; `schedule()` yields cooperatively; `syscall("name", args)` invokes a syscall (open, read, write, sleep, fork). The kernel offers a unified abstraction over the Node and browser hosts.' },
      { title: 'Garbage Collection', body: 'Mark-and-sweep GC runs automatically. Force a cycle with `gc()`. Inspect heap stats with `heapinfo()`.' },
      { title: 'The Bytecode VM', body: 'A stack-based VM executes `.sdevc` files. Opcodes include `LOAD_CONST`, `LOAD_NAME`, `STORE_NAME`, `CALL`, `JUMP`, `JUMP_IF_FALSE`, `RETURN`, `MAKE_FUNCTION`, `BUILD_LIST`, `BUILD_DICT`. The VM is ~3–5× faster than tree-walking.' },
      { title: 'Multi-Language Source', body: 'sdev source can be written in any of 26 languages. The translator normalises keywords at parse time. Set the source language with a `// lang: bg` directive at the top of the file, or `--lang bg` on the CLI.' },
      { title: 'Embedding sdev', body: 'Embed the JS interpreter in a web page with `import { run } from "sdev-interpreter.js"`. Embed the Python interpreter with `from sdev_interpreter import run`.' },
      { title: 'FFI', body: 'Call native libraries via `ffi.load("libm.so").func("sin", ["double"], "double")`. JavaScript host only.' },
    ],
  },
  {
    title: 'Performance',
    intro: 'sdev is fast enough for most scripts. When it is not, here is how to make it faster.',
    sections: [
      { title: 'Choose The Right Runtime', body: 'Tree-walking interpreter: simplest, slowest. Bytecode VM: 3–5× faster. JS interop: native speed for hot loops.' },
      { title: 'Profile Before Optimising', body: 'Use `time` blocks: `time { work() }` prints elapsed milliseconds. Use `profile { work() }` to see a per-function breakdown.' },
      { title: 'Avoid Quadratic Patterns', body: 'Repeated `pluck(coll, 0)` or string concatenation in a loop is O(n²). Prefer `deque()` and `weave([...], "")` respectively.' },
      { title: 'Cache Computations', body: 'Memoise pure functions with `@memo`. Cache external fetches with `cache(ttl: 60)`.' },
      { title: 'Reuse Buffers', body: 'In tight loops, reuse a `buffer(N)` rather than allocating per iteration.' },
      { title: 'Compile To Bytecode', body: 'For long-running services, compile to `.sdevc`. Startup is faster and execution is faster.' },
    ],
  },
  {
    title: 'Best Practices',
    intro: 'Idioms and patterns that make sdev programs delightful to read and maintain.',
    sections: [
      { title: 'Name Things Well', body: 'sdev rewards descriptive names. `forge n be 0` is fine for a counter inside a five-line loop; `forge customers_seen be 0` is better when shared across a function.' },
      { title: 'Prefer Verbs', body: 'Function names should be verbs (`compute`, `render`, `parse`); class names should be nouns (`Customer`, `Invoice`).' },
      { title: 'Keep Functions Small', body: 'Aim for under 20 lines. If a function does two things, split it.' },
      { title: 'Embrace Immutability', body: 'Use `eternal` liberally for values that should not change. Future readers will thank you.' },
      { title: 'Document Intent', body: 'Comments should explain *why*. The code already shows *what*.' },
      { title: 'Test Early, Test Often', body: 'Even one `expect(...)` per function pays for itself within a week.' },
      { title: 'Fail Loudly', body: 'Validate inputs at boundaries. Do not let bad data spread three layers deep before raising.' },
      { title: 'Prefer Composition Over Inheritance', body: 'Mixins (`weave`) and small classes outlast deep hierarchies.' },
    ],
  },
  {
    title: 'A Cookbook of Examples',
    intro: 'Short, complete programs that demonstrate idiomatic sdev. Type these in. Modify them. Break them.',
    sections: [
      { title: 'FizzBuzz', body: CODE(`for i in sequence(1, 100):\n  when:\n    is i % 15 == 0 then speak("FizzBuzz")\n    is i % 3 == 0 then speak("Fizz")\n    is i % 5 == 0 then speak("Buzz")\n    else speak(i)\n  end\nend`) },
      { title: 'Word Count', body: CODE(`forge text be readFile("essay.txt")\nforge words be shatter(text, " ")\nspeak("Word count: " + magnitude(words))`) },
      { title: 'Frequency Histogram', body: CODE(`forge counts be {}\nfor w in shatter(readFile("text.txt"), " "):\n  counts[w] be (counts[w] or 0) + 1\nend\nfor (k, v) in sort(enumerate(counts), key: (p) => -p[1]):\n  speak(k + ": " + v)\nend`) },
      { title: 'Todo App UI', body: CODE(`forge todos be []\nwindow("Todos", 360, 480)\n  heading("My Todos", 2)\n  input("new", "What to do?")\n  button("Add", () => {\n    gather(todos, uiget("new"))\n    uiset("new", "")\n  }, "primary")\n  divider()\n  for t in todos: label("• " + t) end\nendwindow`) },
      { title: 'HTTP Fetch', body: CODE(`async conjure main():\n  forge res be await fetch("https://api.example.com/users")\n  forge users be jsondecode(res.body)\n  for u in users: speak(u.name) end\nend\nawait main()`) },
      { title: 'Bouncing Ball Animation', body: CODE(`canvas(400, 400)\nforge x be 200; forge y be 200; forge dx be 3; forge dy be 2\nframe((t) => {\n  fill("black"); rect(0, 0, 400, 400)\n  fill("cyan"); circle(x, y, 20)\n  x be x + dx; y be y + dy\n  if x below 0 or x above 400 then dx be -dx end\n  if y below 0 or y above 400 then dy be -dy end\n})`) },
      { title: 'Palindrome Checker', body: CODE(`conjure palindrome(s):\n  forge clean be lower(replace(s, " ", ""))\n  return clean equals reverse(clean)\nend\nspeak(palindrome("Race car"))  // => yes`) },
      { title: 'Fibonacci (Memoised)', body: CODE(`@memo\nconjure fib(n):\n  if n below 2 then return n end\n  return fib(n - 1) + fib(n - 2)\nend\nspeak(fib(50))`) },
      { title: 'Calculator UI', body: CODE(`window("Calc", 280, 320)\n  input("a", "First number", "number")\n  input("b", "Second number", "number")\n  row()\n    button("+", () => uiset("r", uiget("a") + uiget("b")))\n    button("−", () => uiset("r", uiget("a") - uiget("b")))\n    button("×", () => uiset("r", uiget("a") * uiget("b")))\n    button("÷", () => uiset("r", uiget("a") / uiget("b")))\n  endrow\n  label("= " + (uiget("r") or "?"))\nendwindow`) },
      { title: 'Web Scraper', body: CODE(`async conjure scrape(url):\n  forge html be (await fetch(url)).body\n  forge titles be regex("<h2>(.*?)</h2>", html, all: yes)\n  return each(titles, (m) => m.groups[0])\nend`) },
      { title: 'Map Of Capitals', body: CODE(`map(48.0, 10.0, 4)\nfor (city, lat, lon) in [("Sofia", 42.7, 23.3), ("Berlin", 52.5, 13.4), ("Paris", 48.9, 2.3)]:\n  marker(lat, lon, city)\nend`) },
    ],
  },
  {
    title: 'Building A Real Application',
    intro: 'A full-length walkthrough: from blank file to a working Markdown notebook with cloud sync.',
    sections: [
      { title: 'Project Layout', body: 'We will create:\n\n- `main.sdev` — entry\n- `lib/storage.sdev` — local + cloud storage\n- `lib/render.sdev` — Markdown renderer\n- `ui/notebook.sdev` — UI window' },
      { title: 'Storage Module', body: CODE(`// lib/storage.sdev\nshare conjure save(key, text):\n  writeFile("notes/" + key + ".md", text)\nend\nshare conjure load(key):\n  return readFile("notes/" + key + ".md")\nend`) },
      { title: 'Render Module', body: 'Use a tiny regex-based Markdown converter, or `summon "gist:abc/markdown.sdev"` for a full one.' },
      { title: 'UI', body: CODE(`window("Notebook", 720, 600)\n  heading("Notebook", 2)\n  input("title", "Note title")\n  textarea("body", "Write your note...", 12)\n  button("Save", () => storage.save(uiget("title"), uiget("body")), "primary")\nendwindow`) },
      { title: 'Wiring It Up', body: '`main.sdev` simply imports the modules and opens the window.' },
      { title: 'Adding Cloud Sync', body: 'When signed in, the workspace auto-syncs. Use `cloudSave("notes", todos)` for additional manual sync of arbitrary data.' },
      { title: 'Publishing', body: 'Export the project as a gist with `sdev publish` and share the URL.' },
    ],
  },
  {
    title: 'Frequently Asked Questions',
    intro: 'Real questions from real sdev users.',
    sections: [
      { title: 'Is sdev fast?', body: 'For interpreted execution, performance is on par with Python. The bytecode compiler (`.sdevc`) gives a 3–5× speedup. For hot loops, drop into `js { ... }` interop.' },
      { title: 'Can I use it in production?', body: 'sdev is best suited for scripting, education, prototyping, internal tools, and embedded scenarios. Production web backends remain a stretch — but it is improving.' },
      { title: 'Why not just use Python?', body: 'Python is excellent. sdev exists for those who want a *more readable* alternative — closer to spoken English than algebraic shorthand — with a built-in UI toolkit, mapping, and 26-language source support.' },
      { title: 'Why two runtimes?', body: 'JavaScript runs everywhere a browser does — including the web IDE — and is great for UI/maps. Python is the default in scientific and pedagogic environments. Strict feature parity means you can pick either.' },
      { title: 'Where do I report bugs?', body: 'Open an issue on the GitHub repository linked from the website footer.' },
      { title: 'Can I contribute?', body: 'Yes! sdev is open source. Pull requests for new builtins, language features, and translations are welcome.' },
      { title: 'How do I keep my files between sessions?', body: 'Sign in. The IDE auto-syncs your entire workspace — files, folders, open tabs — to the cloud. Reload anywhere; pick up where you left off.' },
      { title: 'Why "forge" instead of "let"?', body: '`forge` evokes creation. `let` evokes "permitting" — passive. Active verbs make code feel like *doing*, not *requesting*.' },
    ],
  },
  {
    title: 'Glossary',
    intro: 'Quick definitions of key terms.',
    sections: [
      { title: 'A–F', body: '**Anonymous function** — a function without a name, created with `=>`.\n**Bind** — to associate a name with a value.\n**Bytecode** — the compact instruction format produced by `--compile`.\n**Closure** — a function that captures variables from its lexical scope.\n**Conjure** — keyword to declare a function.\n**Eternal** — modifier for immutable bindings.\n**Forge** — keyword to declare a new variable.' },
      { title: 'G–N', body: '**Gist** — a remote sdev module fetched via `summon`.\n**Kernel** — the virtual OS layer providing tasks and syscalls.\n**Lambda** — synonym for anonymous function.\n**Memo** — decorator that caches function results.\n**Module** — a `.sdev` file imported via `summon`.\n**Morph** — built-in for type conversion.\n**Mutation** — changing the value of a binding.' },
      { title: 'O–Z', body: '**Object** — instance of a class.\n**Promise** — a value that will arrive later.\n**Reactive value** — a UI-bound value managed by `uiget`/`uiset`.\n**Summon** — keyword to import a module or instantiate a class.\n**Tail call** — a function call in tail position; optimised when the function is `tailcall`.\n**VM** — the bytecode virtual machine.\n**Yield** — produce a value from a generator.' },
    ],
  },
  {
    title: 'Design Notes',
    intro: 'Why sdev looks the way it looks. Skip if you only want to write code.',
    sections: [
      { title: 'Verbs Over Symbols', body: 'Symbols read fast for experts and slow for newcomers. Verbs read pleasantly aloud. We chose verbs.' },
      { title: 'Why `end` And Not Indentation', body: 'Significant indentation is fragile across editors and chats. Explicit `end` survives copy-paste, AI prompts, and email.' },
      { title: 'Two Runtimes, One Language', body: 'JavaScript and Python cover most environments where sdev would land. We accepted the cost of duplicating work to keep both groups happy.' },
      { title: 'Why A UI Toolkit Is Built In', body: 'A language without a way to draw a button is a language for tutorials. A language with one is a language for tools.' },
      { title: 'Multi-Language Source', body: 'Programming should not be gated on English literacy. The translator is bidirectional and lossless.' },
      { title: 'Inspirations', body: 'Lua, Python, Smalltalk, Ruby, and AppleScript. Anti-inspirations: Brainfuck, Perl golf, and templating DSLs.' },
    ],
  },
  {
    title: 'Appendices',
    intro: '',
    sections: [
      { title: 'A. Keyword Reference', body: 'Complete keyword list:\n\n`' + KEYWORDS.join('`, `') + '`' },
      { title: 'B. Operator Reference', body: '`+ - * / % ** //`, `== != < > <= >=`, `and or not`, `equals differs above below`, `in`, `=>`, `|>`.' },
      { title: 'C. Built-in Function Index', body: 'See Chapter 17 (The Standard Library). The complete index is in `SDEV_DOCUMENTATION.md`.' },
      { title: 'D. Source Languages', body: 'sdev source files may be written in: English, Bulgarian, Russian, Spanish, French, German, Italian, Portuguese, Polish, Romanian, Ukrainian, Greek, Turkish, Arabic, Hebrew, Hindi, Chinese (Simplified), Chinese (Traditional), Japanese, Korean, Vietnamese, Thai, Indonesian, Dutch, Swedish, Czech.' },
      { title: 'E. Bytecode Opcodes', body: '`LOAD_CONST`, `LOAD_NAME`, `STORE_NAME`, `LOAD_ATTR`, `STORE_ATTR`, `LOAD_INDEX`, `STORE_INDEX`, `BINARY_OP`, `UNARY_OP`, `CALL`, `RETURN`, `JUMP`, `JUMP_IF_FALSE`, `JUMP_IF_TRUE`, `MAKE_FUNCTION`, `MAKE_CLOSURE`, `BUILD_LIST`, `BUILD_DICT`, `IMPORT`, `RAISE`, `TRY_BEGIN`, `TRY_END`, `YIELD`, `AWAIT`, `SPAWN`, `HALT`.' },
      { title: 'F. Syscall Table', body: '`open`, `close`, `read`, `write`, `seek`, `stat`, `mkdir`, `rmdir`, `unlink`, `rename`, `sleep`, `fork`, `wait`, `kill`, `pipe`, `socket`, `connect`, `listen`, `accept`, `send`, `recv`, `time`, `getenv`, `setenv`, `gc`.' },
      { title: 'G. Error Code Index', body: '`E_TYPE`, `E_VALUE`, `E_INDEX`, `E_KEY`, `E_IO`, `E_NET`, `E_TIMEOUT`, `E_SYNTAX`, `E_NAME`, `E_ATTR`, `E_DIVZERO`, `E_OVERFLOW`, `E_RECURSION`, `E_CANCELLED`, `E_INTERNAL`.' },
      { title: 'H. CLI Flag Reference', body: '`--repl`, `--compile <file>`, `--exec <file>`, `--lang <code>`, `--ast`, `--time`, `--profile`, `--lint`, `--format`, `--test`, `--version`, `--help`.' },
      { title: 'I. Index of Examples', body: 'Bouncing ball (Ch.14), Calculator UI (Ch.20), Capitals map (Ch.20), FizzBuzz (Ch.20), Frequency histogram (Ch.20), Notebook app (Ch.21), Palindrome (Ch.20), Todo app (Ch.20), Web scraper (Ch.20), Word count (Ch.20).' },
    ],
  },
];

// ---------- Bulgarian Chapters ----------

const BG_CHAPTERS: Chapter[] = [
  {
    title: 'Въведение',
    intro: 'Добре дошли в **Книгата за sdev** — окончателният, изчерпателен наръчник за програмния език sdev. sdev е модерен, изразителен език с уникално четим синтаксис (`forge`, `be`, `speak`, `conjure`, `summon`), създаден да направи кода да изглежда като проза, без да жертва мощта, скоростта или изразителността.\n\nТази книга е *дълга*. Това е нарочно. Програмните езици са богати светове, а sdev — с четимия си синтаксис, два различни рънтайма, UI инструментариум, ядро, байткод VM и поддръжка на 26 езика — има повече повърхност от повечето.',
    sections: [
      { title: 'Защо sdev?', body: 'sdev е създаден, за да преодолее пропастта между *говоренето за код* и *писането на код*. Класическите езици използват алгебрични съкращения (`x = 1`, `def`, `var`). sdev ги заменя с глаголи и съществителни, които носят смисъл: `forge x be 1`. Резултатът е код, който се чете като рецепта или есе.\n\nsdev също приема сериозно идеята, че **един език трябва да идва с всичко необходимо**: UI инструментариум, графичен canvas, картографски API, планировчик в стил ядро, байткод VM, AI инструменти и преводи на ключовите думи на 26 езика.' },
      { title: 'Кратка история', body: 'sdev започна като експеримент в *проза-подобно* програмиране. Първият интерпретатор беше 400-редов tree-walker. От там се разрасна в два паралелни рънтайма (JavaScript и Python), байткод компилатор, виртуално ядро и IDE в браузъра.' },
      { title: 'За кого е тази книга', body: 'Тази книга е за всички: пълни начинаещи, професионални програмисти, преподаватели и дизайнери на езици. Всяка глава започва меко и постепенно усложнява материала.' },
      { title: 'Как да използвате книгата', body: 'Прочетете я последователно първия път. Всеки пример може да бъде стартиран в **онлайн IDE** на https://s-dev.lovable.app или с офлайн интерпретатори. Пишете примерите — не само ги четете.' },
      { title: 'Конвенции', body: 'Кодовите блокове използват синтаксиса `sdev`. Изходът е показан в `// =>` коментари. Бележки **СЪВЕТ**, **ВНИМАНИЕ** и **ЗАДЪЛБОЧЕНО** маркират важна информация.' },
      { title: 'Първа глътка', body: CODE(`forge greet be conjure(name): "Здравей, " + name end\nspeak(greet("свят"))\n// => Здравей, свят`) },
    ],
  },
  {
    title: 'Първи стъпки',
    intro: 'В тази глава ще инсталирате sdev (или ще пропуснете инсталацията, използвайки уеб IDE), ще напишете първата си програма и ще разберете компонентите на sdev проект.',
    sections: [
      { title: 'Инсталация', body: 'Има няколко начина за стартиране на sdev:\n\n1. **Уеб IDE** — без инсталация, отворете https://s-dev.lovable.app/ide.\n2. **JavaScript интерпретатор** — `node sdev-interpreter.js моят-файл.sdev`.\n3. **Python интерпретатор** — `python sdev-interpreter.py моят-файл.sdev`.\n4. **VS Code разширение** — `.vsix` от менюто Downloads.\n5. **Windows инсталатор** — пакетен инсталатор с миниатюрен редактор.' },
      { title: 'Вашата първа програма', body: CODE(`speak("Здравей, свят!")`) + '\n\nСтартирайте го. Поздравления — вие сте sdev програмист.' },
      { title: 'REPL', body: 'Стартирайте REPL с `python sdev-interpreter.py` без аргументи. Въвеждайте изрази и те ще бъдат изчислявани веднага. Команди: `:quit`, `:reset`, `:load`, `:save`, `:type`.' },
      { title: 'Структура на проекта', body: 'Типичен sdev проект има `main.sdev`, папка `lib/` с модули, папка `assets/`, и `README.md`. Няма задължително оформление.' },
      { title: 'Стартиране от IDE', body: 'В уеб IDE натиснете `Ctrl+Enter` (или `Cmd+Enter`) за изпълнение. Output показва текста; App панелът показва UI; Canvas показва графика; Map показва Leaflet.' },
      { title: 'Анатомия на програма', body: 'Един sdev файл е поредица от изрази. Включва декларации, контролни структури, дефиниции на функции и класове, и импорти. Отстъпите са за хората; `end` е за парсера.' },
      { title: 'Чести грешки за начинаещи', body: '- Забравяне на `end` след `if`, `while` или `conjure`.\n- Използване на `=` вместо `be`. И двете работят; `be` е каноничното.\n- Смесване на `yes`/`no` с `true`/`false`. Изберете един стил.' },
    ],
  },
  {
    title: 'Променливи и стойности',
    intro: 'В sdev създавате променливи с `forge` и ги обвързвате с `be`. Стойностите са динамично типизирани.',
    sections: [
      { title: 'Forge', body: CODE(`forge name be "Ада"\nforge age be 36`) + '\n\nПреобвързване без `forge` запазва променливата в първоначалния обхват.' },
      { title: 'Шест примитивни типа', body: '`number`, `string`, `boolean` (`yes`/`no`), `void` (`nothing`), `collection`, `function`.' },
      { title: 'Инспекция на тип', body: '`essence(value)` връща типа като низ.' },
      { title: 'Преобразуване', body: '`morph(value, "type")` преобразува типове.' },
      { title: 'Константи', body: '`eternal forge PI be 3.14159` — не може да бъде преобвързано.' },
      { title: 'Правила за именуване', body: 'Идентификаторите започват с буква или подчертавка. snake_case за променливи, PascalCase за класове.' },
      { title: 'Обхват', body: 'Лексикален обхват. Функциите образуват затваряния (closures).' },
      { title: 'Истинност', body: 'Falsy: `no`, `nothing`, `0`, `""`, празна колекция.' },
      { title: 'Числа', body: '64-битови с плаваща запетая с бърз път за цели числа. `bigint(n)` за произволна точност.' },
      { title: 'Низове', body: 'Неизменни Unicode. Тройни кавички запазват редовете. Backtick поддържа `${интерполация}`.' },
    ],
  },
  {
    title: 'Оператори и изрази',
    intro: 'sdev поддържа стандартни оператори с английски псевдоними.',
    sections: [
      { title: 'Аритметика', body: '`+`, `-`, `*`, `/`, `%`, `**`, `//`.' },
      { title: 'Сравнение', body: '`==`, `!=`, `<`, `>`, `<=`, `>=`. Псевдоними: `equals`, `differs`, `above`, `below`.' },
      { title: 'Логически', body: '`and`, `or`, `not` (с късо съединение).' },
      { title: 'Низови', body: 'Конкатенация с `+`. Повторение с `*`. Интерполация с backtick.' },
      { title: 'Принадлежност', body: '`x in coll`.' },
      { title: 'Pipeline', body: '`"  hi  " |> trim |> upper |> speak`.' },
      { title: 'Приоритет', body: 'От най-стегнат до най-слаб: `**`, унарен, `* / // %`, `+ -`, сравнения, `and`, `or`, `|>`, присвояване.' },
    ],
  },
  {
    title: 'Контролен поток',
    intro: 'sdev предлага познати контролни структури с английски привкус.',
    sections: [
      { title: 'If/Then/Else', body: CODE(`if score above 90 then\n  speak("Отлично")\nelse\n  speak("Опитай пак")\nend`) },
      { title: 'When', body: CODE(`when:\n  is x below 0 then speak("отрицателно")\n  is x equals 0 then speak("нула")\n  else speak("положително")\nend`) },
      { title: 'While и until', body: CODE(`while count below 10:\n  count be count + 1\nend`) },
      { title: 'For ... in', body: CODE(`for name in ["Ада", "Грейс"]: speak(name) end`) },
      { title: 'Escape и skip', body: '`escape` напуска цикъл; `skip` прескача итерация.' },
      { title: 'Етикетирани цикли', body: '`label name:` + `escape name` за вложени цикли.' },
      { title: 'Match', body: 'Деструктуриране: `forge [a, *rest] be [1,2,3]`.' },
    ],
  },
  {
    title: 'Функции',
    intro: 'Функциите са обекти от първи клас.',
    sections: [
      { title: 'Дефиниция', body: CODE(`conjure greet(name be "непознат"):\n  speak("Здравей, " + name)\nend`) },
      { title: 'Аргументи по подразбиране', body: 'Стойности с `be`. Извикване с ключови думи: `greet(name: "Ада")`.' },
      { title: 'Variadic', body: '`*items` и `**opts`.' },
      { title: 'Връщане', body: '`return value` за ранен изход.' },
      { title: 'Ламбди', body: '`forge double be (n) => n * 2`.' },
      { title: 'Затваряния', body: 'Функциите улавят външни променливи.' },
      { title: 'Higher-order', body: '`each`, `sift`, `fold`, `seek`.' },
      { title: 'Рекурсия', body: 'Поддържа неограничена рекурсия. `tailcall` модификатор за tail-call оптимизация.' },
      { title: 'Генератори', body: 'Функции с `yield` връщат итератори.' },
      { title: 'Декоратори', body: '`@logged conjure work(): ... end`.' },
    ],
  },
  {
    title: 'Колекции',
    intro: 'Списъци и речници.',
    sections: [
      { title: 'Списъци', body: CODE(`forge nums be [1, 2, 3]\nspeak(nums[0])\ngather(nums, 4)`) },
      { title: 'Речници', body: CODE(`forge user be {name: "Ада", age: 36}\nspeak(user.name)`) },
      { title: 'Срязване', body: '`portion(coll, start, end?)`.' },
      { title: 'Map/Filter/Reduce', body: '`each`, `sift`, `fold`.' },
      { title: 'Множества', body: '`unique(coll)`, `set(coll)`.' },
      { title: 'Кортежи', body: '`(a, b)` — неизменни.' },
      { title: 'Итерация', body: '`for ... in`, `enumerate`, `zip`.' },
      { title: 'Производителност', body: 'Списъци: O(1) добавяне. Речници: O(1) търсене. `pluck(coll, 0)` е O(n).' },
    ],
  },
  {
    title: 'Низове задълбочено',
    intro: 'Текстът е навсякъде — заслужава отделна глава.',
    sections: [
      { title: 'Литерали', body: '`\'\'`, `""`, `"""..."""`, и backtick за интерполация.' },
      { title: 'Индексиране', body: 'Низовете са индексируеми. Неизменни.' },
      { title: 'Търсене', body: '`contains`, `indexOf`, `regex`.' },
      { title: 'Манипулация', body: '`upper`, `lower`, `trim`, `replace`, `shatter`, `weave`.' },
      { title: 'Кодиране', body: '`base64encode`, `urlencode`, `hexencode`.' },
      { title: 'Форматиране', body: 'Backtick интерполация или `format`.' },
      { title: 'Регулярни изрази', body: '`regex(pattern, s)` връща обект с `groups`.' },
      { title: 'Unicode', body: 'Низовете са последователности от Unicode codepoints. `locale("bg_BG")` за локализирани операции.' },
    ],
  },
  {
    title: 'Обектно-ориентирано програмиране',
    intro: 'Класове с `essence`, инстанции със `summon`, наследяване с `extends`.',
    sections: [
      { title: 'Дефиниция на клас', body: CODE(`essence Dog:\n  share name\n  conjure init(name): me.name be name end\n  conjure bark(): speak(me.name + " лае!") end\nend`) },
      { title: 'Инстанции', body: CODE(`forge rex be summon Dog(name: "Рекс")\nrex.bark()`) },
      { title: 'Наследяване', body: '`essence Puppy extends Dog: ... end`. `ancestor.method()` извиква базовия.' },
      { title: 'Class методи', body: '`static share` и `static conjure`.' },
      { title: 'Mixins', body: '`essence Bird weave Flyable, Singable: end`.' },
      { title: 'Претоварване на оператори', body: '`__add__`, `__eq__`, `__str__`.' },
      { title: 'Свойства', body: '`@property` и `@setter`.' },
      { title: 'Абстрактни класове', body: '`abstract conjure name()`.' },
    ],
  },
  {
    title: 'Обработка на грешки',
    intro: 'Програмите се провалят. sdev предлага точни инструменти.',
    sections: [
      { title: 'Raise', body: '`raise "Без гориво"` или `raise FuelError(...)`.' },
      { title: 'Attempt/Rescue/Finally', body: CODE(`attempt:\n  forge data be readFile("missing.txt")\nrescue err:\n  speak(err.message)\nfinally:\n  speak("край")\nend`) },
      { title: 'Типове грешки', body: '`TypeError`, `ValueError`, `IOError`, `KeyError`, `IndexError`, `NetworkError`, `TimeoutError`.' },
      { title: 'Множество rescue', body: 'Свързани с тип на грешката.' },
      { title: 'Re-raise', body: '`raise` без аргумент в `rescue`.' },
      { title: 'Stack traces', body: 'Грешките имат `.trace` с рамки.' },
      { title: 'Asserts', body: '`ensure(условие, "съобщение")`.' },
      { title: 'Идиоми', body: 'Валидирайте на границите. Не превръщайте rescue в тих поглъщач.' },
    ],
  },
  {
    title: 'Конкурентност',
    intro: 'Кооперативна конкурентност.',
    sections: [
      { title: 'Async функции', body: '`async conjure ...` + `await`.' },
      { title: 'Dispatch и await', body: '`forge p be dispatch f()` + `await p`.' },
      { title: 'Паралел', body: '`await all([...])`, `await any([...])`, `await race([...])`.' },
      { title: 'Канали', body: '`channel()`, `send`, `receive`.' },
      { title: 'Отказване', body: '`cancel(p)`, `rescue CancelledError`.' },
      { title: 'Време', body: '`await delay(1000)`, `every(ms, fn)`.' },
      { title: 'Ядро', body: 'Всички задачи живеят във виртуално ядро.' },
    ],
  },
  {
    title: 'Модули и библиотеки',
    intro: 'Реалните програми се състоят от много файлове.',
    sections: [
      { title: 'Локални модули', body: '`summon "./utils.sdev" as u`.' },
      { title: 'Gist пакети', body: 'Декентрализиран регистър чрез GitHub Gists.' },
      { title: 'Версии', body: '`summon "gist:abc@v1.2.0/util.sdev"`.' },
      { title: 'Манифести', body: 'Файл `manifest.sdev` декларира зависимости.' },
      { title: 'Авторство', body: 'Публични `conjure` и `essence` са експортирани. `share private` скрива.' },
      { title: 'Обхват', body: 'Всеки модул има собствен глобален обхват.' },
      { title: 'Динамично зареждане', body: '`loadModule(url)`.' },
    ],
  },
  {
    title: 'UI инструментариум',
    intro: 'Декларативен UI: прозорци, форми, дашбордове.',
    sections: [
      { title: 'Прозорци', body: CODE(`window("Моето приложение", 480, 600)\n  heading("Здравей", 1)\nendwindow`) },
      { title: 'Заглавия и текст', body: '`heading(text, level)`, `label(text)`, `paragraph(text)`.' },
      { title: 'Бутони', body: '`button("Натисни", () => ..., "primary")`. Варианти: primary, secondary, ghost, destructive, link.' },
      { title: 'Полета', body: '`input("име", "плейсхолдър", "kind")`. Видове: text, number, password, email, url.' },
      { title: 'Многоредови полета', body: '`textarea("body", "...", 10)`.' },
      { title: 'Чекбоксове и радиа', body: '`checkbox(bind, label)`, `radio(bind, value, label)`.' },
      { title: 'Слайдъри и select', body: '`slider`, `select`.' },
      { title: 'Таблици', body: '`table(["Име","Възраст"], [["Ада",36]])`.' },
      { title: 'Tabs', body: 'tabs/endtabs + tab/endtab.' },
      { title: 'Менюта', body: 'menu/endmenu + menuitem.' },
      { title: 'Подредба', body: 'row/endrow, column/endcolumn, group/endgroup.' },
      { title: 'Реактивни стойности', body: '`uiget(name)` и `uiset(name, value)`.' },
      { title: 'Събития', body: 'Бутоните и менютата приемат callback.' },
      { title: 'Персонализация', body: 'Дикционар с опции като последен аргумент: размер, икона, URL.' },
      { title: 'Пълен пример', body: CODE(`forge todos be []\nwindow("Todos", 360, 480)\n  input("new", "Какво да направя?")\n  button("Добави", () => { gather(todos, uiget("new")); uiset("new", "") }, "primary")\n  for t in todos: label("• " + t) end\nendwindow`) },
    ],
  },
  {
    title: 'Графика и canvas',
    intro: '2D рисуване и анимация.',
    sections: [
      { title: 'Canvas', body: '`canvas(width, height)`.' },
      { title: 'Примитиви', body: '`fill`, `stroke`, `rect`, `circle`, `line`, `polygon`, `text`.' },
      { title: 'Цветове', body: 'CSS имена, `#rrggbb`, `rgb()`, `hsl()`, `rgba()`.' },
      { title: 'Анимация', body: '`frame(fn)`.' },
      { title: 'Изображения', body: '`loadImage`, `drawImage`.' },
      { title: 'Трансформации', body: '`translate`, `rotate`, `scale`, `push`, `pop`.' },
      { title: 'Вход', body: '`onmouse`, `onkey`.' },
      { title: 'Подскачаща топка', body: CODE(`canvas(400, 400)\nforge x be 200; forge y be 200; forge dx be 3; forge dy be 2\nframe((t) => {\n  fill("black"); rect(0, 0, 400, 400)\n  fill("cyan"); circle(x, y, 20)\n  x be x + dx; y be y + dy\n})`) },
    ],
  },
  {
    title: 'Карти и ГИС',
    intro: 'Интеграция с Leaflet.',
    sections: [
      { title: 'Карта', body: '`map(lat, lon, zoom)`.' },
      { title: 'Маркери', body: '`marker(lat, lon, "етикет")`.' },
      { title: 'Tile слоеве', body: '`tiles(url, opts)`. Стилове: osm, dark, satellite.' },
      { title: 'Полилинии', body: '`polyline([[lat,lon],...], "color")`.' },
      { title: 'Полигони', body: '`polygon([[lat,lon],...], "color")`.' },
      { title: 'GeoJSON', body: '`geojson(url)`.' },
      { title: 'Heatmaps', body: '`heatmap(points)`, `cluster(points)`.' },
      { title: 'Събития', body: '`onclick((lat, lon) => ...)`.' },
      { title: 'Маршрутиране', body: '`distance(p1, p2)`, `route(from, to)`.' },
    ],
  },
  {
    title: 'Стандартна библиотека',
    intro: 'Справочник.',
    sections: [
      { title: 'Таблица', body: '| Функция | Описание |\n|---|---|\n' + BUILTINS_TABLE.slice(0, 40).map(([n,d]) => `| \`${n}\` | ${d} |`).join('\n') },
      { title: 'I/O', body: '`speak`, `whisper`, `shout`, `ask`, `readFile`, `writeFile`, `appendFile`.' },
      { title: 'Математика', body: '`magnitude`, `least`, `greatest`, `root`, `random`, `sin`, `cos`, `pi`.' },
      { title: 'Колекции', body: '`gather`, `pluck`, `each`, `sift`, `fold`, `zip`, `enumerate`.' },
      { title: 'Низове', body: '`upper`, `lower`, `trim`, `replace`, `shatter`, `weave`.' },
      { title: 'Време', body: '`now`, `today`, `delay`, `format`.' },
      { title: 'Мрежа', body: '`fetch`, `websocket`, `download`.' },
      { title: 'Система', body: '`env`, `argv`, `exit`, `osinfo`.' },
      { title: 'Кодиране', body: '`base64encode`, `hexencode`, `jsonencode`.' },
      { title: 'Криптография', body: '`hash`, `hmac`, `uuid`, `randomBytes`.' },
    ],
  },
  {
    title: 'Инструменти',
    intro: 'Редактори, линтер, дебъгер, компилатор.',
    sections: [
      { title: 'Уеб IDE', body: 'Пълнофункционално IDE на https://s-dev.lovable.app/ide.' },
      { title: 'VS Code разширение', body: 'Изтеглете `.vsix`.' },
      { title: 'CLI', body: 'Флагове: `--repl`, `--compile`, `--exec`, `--lang`, `--ast`, `--time`.' },
      { title: 'Bytecode компилатор', body: '`--compile main.sdev` → `main.sdevc`.' },
      { title: 'sdev асистент', body: 'Вграден AI чатбот.' },
      { title: 'Линтер', body: '`sdev lint file.sdev`.' },
      { title: 'Форматер', body: '`sdev format file.sdev`.' },
      { title: 'Дебъгер', body: '`breakpoint()` пауза в IDE.' },
      { title: 'Тестове', body: '`sdev test` пуска `conjure test_*` функции.' },
    ],
  },
  {
    title: 'Напреднали теми',
    intro: 'Функции за опитни потребители.',
    sections: [
      { title: 'JavaScript Interop', body: '`js { console.log("native") }`. Многоредови блокове споделят обхват.' },
      { title: 'Матрична математика', body: '`matrix`, `matmul`, `inverse`, `transpose`, `det`.' },
      { title: 'Буфери и указатели', body: '`buffer(размер)`, `pointer(стойност)`, `deref(p)`.' },
      { title: 'Виртуално ядро', body: '`spawn(fn)`, `schedule()`, `syscall("име", args)`.' },
      { title: 'Сметоизхвърляне', body: 'Mark-and-sweep GC. Принудете цикъл с `gc()`. `heapinfo()`.' },
      { title: 'Bytecode VM', body: 'Стек-базирана VM. Опкодове: LOAD_CONST, CALL, JUMP, RETURN, MAKE_FUNCTION.' },
      { title: 'Многоезичен код', body: '26 езика. `// lang: bg` директива.' },
      { title: 'Вграждане', body: '`import { run } from "sdev-interpreter.js"` в JS, `from sdev_interpreter import run` в Python.' },
      { title: 'FFI', body: '`ffi.load("libm.so").func(...)`.' },
    ],
  },
  {
    title: 'Производителност',
    intro: 'Как да направите sdev по-бърз, когато е необходимо.',
    sections: [
      { title: 'Изберете рънтайм', body: 'Tree-walker: най-бавен. Bytecode: 3-5× по-бърз. JS interop: native.' },
      { title: 'Профилирайте', body: '`time { ... }`, `profile { ... }`.' },
      { title: 'Избягвайте квадратични шаблони', body: '`pluck(coll, 0)` в цикъл е O(n²). Използвайте `deque`.' },
      { title: 'Кеширане', body: '`@memo` за чисти функции.' },
      { title: 'Преизползвайте буфери', body: 'Един `buffer(N)` извън цикъла.' },
      { title: 'Компилирайте', body: 'За дълготрайни процеси, `--compile`.' },
    ],
  },
  {
    title: 'Добри практики',
    intro: 'Идиоми и шаблони.',
    sections: [
      { title: 'Именувайте добре', body: 'sdev възнаграждава описателните имена.' },
      { title: 'Предпочитайте глаголи', body: 'Имена на функции = глаголи; имена на класове = съществителни.' },
      { title: 'Малки функции', body: 'Под 20 реда.' },
      { title: 'Прегърнете неизменността', body: 'Използвайте `eternal` често.' },
      { title: 'Документирайте намерението', body: 'Коментарите обясняват *защо*.' },
      { title: 'Тествайте рано', body: 'Един `expect` на функция.' },
      { title: 'Проваляйте се шумно', body: 'Валидирайте на границите.' },
      { title: 'Композиция над наследяване', body: 'Mixins (`weave`) надживяват дълбоки йерархии.' },
    ],
  },
  {
    title: 'Готварска книга с примери',
    intro: 'Кратки, пълни програми.',
    sections: [
      { title: 'FizzBuzz', body: CODE(`for i in sequence(1, 100):\n  when:\n    is i % 15 == 0 then speak("FizzBuzz")\n    is i % 3 == 0 then speak("Fizz")\n    is i % 5 == 0 then speak("Buzz")\n    else speak(i)\n  end\nend`) },
      { title: 'Брояч на думи', body: CODE(`forge text be readFile("essay.txt")\nspeak(magnitude(shatter(text, " ")))`) },
      { title: 'Хистограма', body: CODE(`forge counts be {}\nfor w in shatter(readFile("text.txt"), " "):\n  counts[w] be (counts[w] or 0) + 1\nend`) },
      { title: 'Todo приложение', body: CODE(`forge todos be []\nwindow("Todos", 360, 480)\n  input("new", "Какво да направя?")\n  button("Добави", () => { gather(todos, uiget("new")); uiset("new", "") })\n  for t in todos: label(t) end\nendwindow`) },
      { title: 'HTTP заявка', body: CODE(`async conjure main():\n  forge res be await fetch("https://api.example.com")\n  speak(res.body)\nend\nawait main()`) },
      { title: 'Подскачаща топка', body: CODE(`canvas(400, 400)\nforge x be 200; forge y be 200; forge dx be 3; forge dy be 2\nframe((t) => { fill("black"); rect(0,0,400,400); fill("cyan"); circle(x,y,20); x be x+dx; y be y+dy })`) },
      { title: 'Палиндром', body: CODE(`conjure palindrome(s):\n  forge clean be lower(replace(s, " ", ""))\n  return clean equals reverse(clean)\nend`) },
      { title: 'Фибоначи', body: CODE(`@memo\nconjure fib(n):\n  if n below 2 then return n end\n  return fib(n-1) + fib(n-2)\nend`) },
      { title: 'Калкулатор UI', body: CODE(`window("Calc", 280, 320)\n  input("a", "Първо", "number")\n  input("b", "Второ", "number")\n  button("+", () => uiset("r", uiget("a") + uiget("b")))\n  label("= " + (uiget("r") or "?"))\nendwindow`) },
      { title: 'Карта на столици', body: CODE(`map(48.0, 10.0, 4)\nfor (c, lat, lon) in [("София",42.7,23.3),("Берлин",52.5,13.4)]:\n  marker(lat, lon, c)\nend`) },
    ],
  },
  {
    title: 'Изграждане на реално приложение',
    intro: 'От празен файл до работещ Markdown notebook.',
    sections: [
      { title: 'Подредба', body: '`main.sdev`, `lib/storage.sdev`, `lib/render.sdev`, `ui/notebook.sdev`.' },
      { title: 'Storage модул', body: CODE(`share conjure save(key, text):\n  writeFile("notes/" + key + ".md", text)\nend`) },
      { title: 'Render модул', body: 'Малък регекс конвертор или `summon "gist:abc/markdown.sdev"`.' },
      { title: 'UI', body: CODE(`window("Notebook", 720, 600)\n  input("title", "Заглавие")\n  textarea("body", "Пишете...", 12)\n  button("Запис", () => storage.save(uiget("title"), uiget("body")), "primary")\nendwindow`) },
      { title: 'Свързване', body: '`main.sdev` импортира модулите.' },
      { title: 'Облак', body: 'Когато сте логнати, работното пространство автоматично синхронизира.' },
      { title: 'Публикуване', body: '`sdev publish` качва като gist.' },
    ],
  },
  {
    title: 'Често задавани въпроси',
    intro: 'Реални въпроси от реални потребители.',
    sections: [
      { title: 'Бърз ли е sdev?', body: 'Сравнима с Python производителност. Bytecode дава 3-5× ускорение.' },
      { title: 'Може ли в продукция?', body: 'Подходящ за скриптове, образование, прототипи, вътрешни инструменти.' },
      { title: 'Защо не Python?', body: 'sdev съществува за тези, които искат *по-четим* алтернативен синтаксис.' },
      { title: 'Защо два рънтайма?', body: 'JavaScript за уеб, Python за научни среди.' },
      { title: 'Бъгове?', body: 'GitHub issue.' },
      { title: 'Принос?', body: 'Да, sdev е с отворен код.' },
      { title: 'Запазване между сесии?', body: 'Влезте в акаунт. IDE автоматично синхронизира.' },
      { title: 'Защо "forge"?', body: 'Активен глагол; "let" е пасивен.' },
    ],
  },
  {
    title: 'Речник',
    intro: 'Бързи дефиниции.',
    sections: [
      { title: 'А–Й', body: '**Анонимна функция** — без име.\n**Bytecode** — компактният формат от `--compile`.\n**Затваряне** — функция, която улавя външни променливи.\n**Eternal** — модификатор за неизменими обвързвания.' },
      { title: 'К–Р', body: '**Колекция** — списък или речник.\n**Lambda** — синоним за анонимна функция.\n**Memo** — декоратор за кеширане.\n**Модул** — `.sdev` файл.\n**Морф** — за конверсия на типове.' },
      { title: 'С–Я', body: '**Обект** — инстанция на клас.\n**Обещание** — стойност, която ще пристигне по-късно.\n**Реактивна стойност** — UI-обвързана стойност.\n**Tail call** — извикване в опашка; оптимизирано.\n**ВМ** — байткод виртуалната машина.' },
    ],
  },
  {
    title: 'Бележки за дизайна',
    intro: 'Защо sdev изглежда така.',
    sections: [
      { title: 'Глаголи над символи', body: 'Символите четат бързо за експерти и бавно за нови. Глаголите четат приятно.' },
      { title: 'Защо `end`', body: 'Значимите отстъпи са крехки в редактори и чатове. `end` оцелява copy-paste.' },
      { title: 'Два рънтайма', body: 'JavaScript и Python покриват повечето среди.' },
      { title: 'UI вграден', body: 'Език без бутон е език за уроци.' },
      { title: 'Многоезичен', body: 'Програмирането не трябва да е блокирано от английски.' },
      { title: 'Вдъхновения', body: 'Lua, Python, Smalltalk, Ruby, AppleScript.' },
    ],
  },
  {
    title: 'Приложения',
    intro: '',
    sections: [
      { title: 'A. Ключови думи', body: '`' + KEYWORDS.join('`, `') + '`' },
      { title: 'B. Оператори', body: '`+ - * / % ** //`, `== != < > <= >=`, `and or not`, `equals differs above below`, `in`, `=>`, `|>`.' },
      { title: 'C. Вградени функции', body: 'Виж глава "Стандартна библиотека".' },
      { title: 'D. Изходни езици', body: '26 езика, включително български, английски, испански, френски, немски, руски, китайски, японски, корейски и арабски.' },
      { title: 'E. Bytecode опкодове', body: 'LOAD_CONST, LOAD_NAME, STORE_NAME, CALL, JUMP, JUMP_IF_FALSE, RETURN, MAKE_FUNCTION, BUILD_LIST, BUILD_DICT, IMPORT, RAISE, YIELD, AWAIT, SPAWN, HALT.' },
      { title: 'F. Syscalls', body: 'open, close, read, write, sleep, fork, socket, connect, time, gc.' },
      { title: 'G. Кодове на грешки', body: 'E_TYPE, E_VALUE, E_INDEX, E_KEY, E_IO, E_NET, E_TIMEOUT, E_SYNTAX.' },
      { title: 'H. CLI флагове', body: '--repl, --compile, --exec, --lang, --ast, --time, --profile, --lint, --format, --test.' },
      { title: 'I. Индекс на примерите', body: 'Подскачаща топка, Калкулатор, Карта на столици, FizzBuzz, Хистограма, Notebook, Палиндром, Todo, Web scraper, Брояч на думи.' },
    ],
  },
];

function slug(s: string) {
  return s.toLowerCase().replace(/[^a-zа-я0-9]+/gi, '-').replace(/^-|-$/g, '');
}

function render(chapters: Chapter[], title: string, lang: 'en' | 'bg'): string {
  const lines: string[] = [];
  lines.push(`# ${title}\n`);
  lines.push(lang === 'bg'
    ? '_Изчерпателен наръчник за програмния език sdev._\n'
    : '_The comprehensive reference for the sdev programming language._\n');
  lines.push('---\n');
  lines.push(lang === 'bg' ? '## Съдържание\n' : '## Table of Contents\n');
  chapters.forEach((c, i) => {
    lines.push(`${i + 1}. [${c.title}](#${i + 1}-${slug(c.title)})`);
    c.sections.forEach((s, j) => {
      lines.push(`   - ${i + 1}.${j + 1} [${s.title}](#${i + 1}-${j + 1}-${slug(s.title)})`);
    });
  });
  lines.push('\n---\n');
  chapters.forEach((c, i) => {
    lines.push(`\n## ${i + 1}. ${c.title}\n`);
    if (c.intro) lines.push(`${c.intro}\n`);
    c.sections.forEach((s, j) => {
      lines.push(`\n### ${i + 1}.${j + 1} ${s.title}\n`);
      lines.push(`${s.body}\n`);
    });
  });
  lines.push('\n---\n');
  lines.push(lang === 'bg'
    ? '*Край на книгата. Версия 2.0. © sdev език.*\n'
    : '*End of book. Version 2.0. © sdev language.*\n');
  return lines.join('\n');
}

const en = render(EN_CHAPTERS, 'The sdev Book', 'en');
const bg = render(BG_CHAPTERS, 'Книгата за sdev', 'bg');

fs.writeFileSync(path.join('public', 'sdev-book-en.md'), en);
fs.writeFileSync(path.join('public', 'sdev-book-bg.md'), bg);
console.log(`EN: ${en.length} chars (${en.split('\n').length} lines)`);
console.log(`BG: ${bg.length} chars (${bg.split('\n').length} lines)`);
